### ISSUE TITLE
Filters not working with ActiveAdmin 0.6

### ISSUE THREAD

**Issue by markterm** [activeadmin/activeadmin-mongoid#38]
Using filters results in:

```
undefined method `yyyy_contains' for #<Array:0x007fbd7990ed20>

mongoid (3.1.3) lib/mongoid/criteria.rb:510:in `method_missing'
actionpack (3.2.13) lib/action_view/helpers/form_helper.rb:1159:in `value_before_type_cast'
actionpack (3.2.13) lib/action_view/helpers/form_helper.rb:1147:in `value_before_type_cast'
actionpack (3.2.13) lib/action_view/helpers/form_helper.rb:1041:in `block in to_input_field_tag'
actionpack (3.2.13) lib/action_view/helpers/form_helper.rb:1041:in `fetch'
actionpack (3.2.13) lib/action_view/helpers/form_helper.rb:1041:in `to_input_field_tag'
actionpack (3.2.13) lib/action_view/helpers/form_helper.rb:690:in `text_field'
actionpack (3.2.13) lib/action_view/helpers/form_helper.rb:1284:in `text_field'
/Users/markwhi/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/bundler/gems/active_admin-46b5bf8d7ef9/lib/active_admin/inputs/filter_string_input.rb:9:in `block in to_html'
actionpack (3.2.13) lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
actionpack (3.2.13) lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
haml (4.0.2) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
actionpack (3.2.13) lib/action_view/helpers/capture_helper.rb:40:in `capture'
haml (4.0.2) lib/haml/helpers/action_view_mods.rb:59:in `capture_with_haml'
/Users/markwhi/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/bundler/gems/active_admin-46b5bf8d7ef9/lib/active_admin/inputs/filter_base.rb:8:in `input_wrapping'
/Users/markwhi/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/bundler/gems/active_admin-46b5bf8d7ef9/lib/active_admin/inputs/filter_string_input.rb:7:in `to_html'
formtastic (2.2.1) lib/formtastic/helpers/input_helper.rb:240:in `input'
/Users/markwhi/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/bundler/gems/active_admin-46b5bf8d7ef9/lib/active_admin/form_builder.rb:19:in `block in input'
/Users/markwhi/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/bundler/gems/active_admin-46b5bf8d7ef9/lib/active_admin/form_builder.rb:177:in `with_new_form_buffer'
/Users/markwhi/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/bundler/gems/active_admin-46b5bf8d7ef9/lib/active_admin/form_builder.rb:19:in `input'
/Users/markwhi/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/bundler/gems/active_admin-46b5bf8d7ef9/lib/active_admin/filters/forms.rb:11:in `filter'
/Users/markwhi/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/bundler/gems/active_admin-46b5bf8d7ef9/lib/active_admin/filters/forms.rb:80:in `block (2 levels) in active_admin_filters_form_for'
/Users/markwhi/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/bundler/gems/active_admin-46b5bf8d7ef9/lib/active_admin/filters/forms.rb:75:in `each'
/Users/markwhi/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/bundler/gems/active_admin-46b5bf8d7ef9/lib/active_admin/filters/forms.rb:75:in `block in active_admin_filters_form_for'
actionpack (3.2.13) lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
```
