### ISSUE TITLE
Filters are not working with rails 4.0

### ISSUE THREAD

**Issue by max-konin** [activeadmin/activeadmin-mongoid#92]
I am using activeadmin-mongoid (rails4 branch) with Rails 4.0
When I am using this code:

```
filter :post_name, :as => :string
```

it is giving me an error

```
undefined method `_ransackers' for Mongoid::Criteria:Class
```

I have understood that activeadmin now using ransack instead metasearch. But ransack does not support mongoid

There is also an ransack's adapter for mongoid (https://github.com/kristianmandrup/ransack-mongoid). But it not help to me

**Comment by muichkine** [comment]
+1
