### ISSUE TITLE
Upgrade ActiveAdmin to 1.2.x

### ISSUE THREAD

**Issue by boie0025** [activeadmin/activeadmin-mongoid#120]

**Comment by grzegorz-jakubiak** [comment]
@boie0025 I can help with that as well if you want.

**Comment by grzegorz-jakubiak** [comment]
@boie0025 I've started working on it and updated to 1.2. The first error I get is related to filters and method that isn't present in mongoid:
```
undefined method `association_primary_key' for #<Mongoid::Relations::Metadata:0x0000000002742aa0>
```

`association_primary_key` was added to filters after release of activeadmin 1.1 in this commit and it comes from activerecord: https://github.com/activeadmin/activeadmin/commit/78028761adffd6fe25a91b8b4c61c8c07d9e1a1d#diff-4d08d3c1322dabe608c2079b868d13fd

I don't know how I should go about fixing this issue. Do you maybe have any suggestions or tips for me?

**Comment by boie0025** [comment]
Hi @grzegorz-jakubiak, Sorry, I missed this earlier.  Can you push up a branch to your copy with this issue?  I'll poke around and see if I can come up with something.  It may just have something to do with the specific filters used in the test.  May have to patch something.. but this whole project is full of patches, so that's probably fine.

**Comment by grzegorz-jakubiak** [comment]
@boie0025 I pushed my branch: https://github.com/activeadmin/activeadmin-mongoid/tree/activeadmin-1.2
