### ISSUE TITLE
Undefined method 'metasearch' after upgrading from 0.5.1

### ISSUE THREAD

**Issue by levity** [activeadmin/activeadmin-mongoid#36]
I had activeadmin-mongoid working mostly fine on 0.5.1, and upgraded to 0.6.0 in an attempt to resolve an issue with scopes on nested resources. however i've now run into this other issue...
